import http from 'node:http';
import { readFile, stat } from 'node:fs/promises';
import { createHash, randomBytes, scrypt as scryptCallback, timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';
import { extname, join, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';
import { initializeDatabase, query, transaction, databaseMode, closeDatabase } from './database.mjs';
import { exerciseCatalog } from './exercise-catalog.mjs';

const scrypt = promisify(scryptCallback);
const IS_PRODUCTION = process.env.NODE_ENV === 'production';
const HOST = process.env.HOST || '127.0.0.1';
const PORT = Number(process.env.PORT || 4173);
const APP_ORIGIN = process.env.APP_ORIGIN || `http://${HOST}:${PORT}`;
if(IS_PRODUCTION&&(!process.env.DATABASE_URL||!APP_ORIGIN.startsWith('https://')||String(process.env.METRICS_TOKEN||'').length<32))throw new Error('Production requires DATABASE_URL, an HTTPS APP_ORIGIN, and a 32+ character METRICS_TOKEN.');
const ROOT = fileURLToPath(new URL('.', import.meta.url));
const COOKIE = 'ptrainer_sid';
const SESSION_TTL = 60 * 60 * 1000;
const types = { '.html':'text/html; charset=utf-8', '.css':'text/css; charset=utf-8', '.js':'text/javascript; charset=utf-8', '.json':'application/json; charset=utf-8', '.svg':'image/svg+xml' };

const users = new Map();
const usersByEmail = new Map();
const sessions = new Map();
const invitations = new Map();
const relationships = new Map();
const workoutTemplates = new Map();
const assignments = new Map();
const workoutSaves = new Map();
const rateBuckets = new Map();
const passwordResets = new Map();
const telemetry={startedAt:Date.now(),requests:0,errors:0,totalDurationMs:0,byStatus:new Map()};

const id = prefix => `${prefix}_${randomBytes(10).toString('hex')}`;
const tokenDigest = token => createHash('sha256').update(token).digest('base64url');
const publicUser = user => ({ id:user.id, name:user.name, email:user.email, role:user.role });
const cleanEmail = value => typeof value === 'string' ? value.trim().toLowerCase() : '';
const validEmail = value => value.length <= 254 && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
const validName = value => typeof value === 'string' && value.trim().length >= 2 && value.trim().length <= 80;
const validPassword = value => typeof value === 'string' && value.length >= 10 && value.length <= 128 && /[a-z]/.test(value) && /[A-Z]/.test(value) && /\d/.test(value) && /[^A-Za-z0-9]/.test(value);
function normalizeWorkoutInput(body){const name=typeof body.name==='string'?body.name.trim():'',description=typeof body.description==='string'?body.description.trim():'',dueDate=String(body.dueDate||'').slice(0,10),parsedDate=dueDate?new Date(`${dueDate}T00:00:00.000Z`):null,validDate=!dueDate||/^\d{4}-\d{2}-\d{2}$/.test(dueDate)&&!Number.isNaN(parsedDate.getTime())&&parsedDate.toISOString().slice(0,10)===dueDate;if(name.length<3||name.length>100||description.length>500||!Array.isArray(body.exercises)||body.exercises.length<1||body.exercises.length>30||!validDate)return null;const exercises=body.exercises.map(item=>({name:String(item.name||'').trim(),sets:Number(item.sets),reps:Number(item.reps),restSeconds:Number(item.restSeconds)}));if(exercises.some(item=>item.name.length<2||item.name.length>100||!Number.isInteger(item.sets)||item.sets<1||item.sets>20||!Number.isInteger(item.reps)||item.reps<1||item.reps>1000||!Number.isInteger(item.restSeconds)||item.restSeconds<0||item.restSeconds>900))return null;return{name,description,dueDate,exercises}}
const log=(level,event,fields={})=>console.log(JSON.stringify({timestamp:new Date().toISOString(),level,event,...fields}));
const routeLabel=path=>String(path||'/').replace(/^\/api\/invitations\/[^/]+\/accept$/,'/api/invitations/:token/accept').replace(/^\/api\/assigned-workouts\/[^/]+\/logs$/,'/api/assigned-workouts/:id/logs').replace(/^\/api\/assigned-workouts\/[^/]+$/,'/api/assigned-workouts/:id').replace(/^\/api\/notifications\/[^/]+\/read$/,'/api/notifications/:id/read').replace(/^\/api\/relationships\/[^/]+\/[^/]+$/,'/api/relationships/:trainerId/:traineeId');

await initializeDatabase();

async function hashPassword(password, salt = randomBytes(16)) {
  const hash = await scrypt(password, salt, 64, { N:16384, r:8, p:1, maxmem:64*1024*1024 });
  return `${salt.toString('base64url')}.${Buffer.from(hash).toString('base64url')}`;
}
async function verifyPassword(password, stored) {
  const [saltText, hashText] = stored.split('.');
  if (!saltText || !hashText) return false;
  const expected = Buffer.from(hashText, 'base64url');
  const actual = Buffer.from(await scrypt(password, Buffer.from(saltText, 'base64url'), expected.length, { N:16384, r:8, p:1, maxmem:64*1024*1024 }));
  return actual.length === expected.length && timingSafeEqual(actual, expected);
}
async function createUser({ name, email, password, role }) {
  const normalizedEmail=cleanEmail(email);const existing=await query('SELECT id,email,password_hash,name,role,status,created_at FROM users WHERE email=$1',[normalizedEmail]);
  if(existing.rowCount){const row=existing.rows[0],user={id:row.id,name:row.name,email:row.email,passwordHash:row.password_hash,role:row.role,status:row.status,createdAt:row.created_at};users.set(user.id,user);usersByEmail.set(user.email,user.id);return user}
  const user = { id:id('usr'), name:name.trim(), email:cleanEmail(email), passwordHash:await hashPassword(password), role, status:'ACTIVE', createdAt:new Date().toISOString() };
  await query('INSERT INTO users(id,email,password_hash,name,role,status,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$7)',[user.id,user.email,user.passwordHash,user.name,user.role,user.status,user.createdAt]);users.set(user.id, user); usersByEmail.set(user.email, user.id); return user;
}

const storedUsers=await query('SELECT id,email,password_hash,name,role,status,created_at FROM users');for(const row of storedUsers.rows){const user={id:row.id,name:row.name,email:row.email,passwordHash:row.password_hash,role:row.role,status:row.status,createdAt:row.created_at};users.set(user.id,user);usersByEmail.set(user.email,user.id)}
const storedRelationships=await query('SELECT trainer_id,trainee_id,status,created_at FROM trainer_trainee_relationships');for(const row of storedRelationships.rows)relationships.set(`${row.trainer_id}:${row.trainee_id}`,{trainerId:row.trainer_id,traineeId:row.trainee_id,status:row.status,createdAt:row.created_at});
const storedTemplates=await query('SELECT id,trainer_id,name,description,version,exercises,created_at FROM workout_templates WHERE archived_at IS NULL');for(const row of storedTemplates.rows)workoutTemplates.set(row.id,{id:row.id,trainerId:row.trainer_id,name:row.name,description:row.description,version:row.version,exercises:row.exercises,createdAt:row.created_at});
const storedAssignments=await query('SELECT id,template_id,trainer_id,trainee_id,template_snapshot,due_date,status,created_at FROM assigned_workouts');for(const row of storedAssignments.rows)assignments.set(row.id,{id:row.id,templateId:row.template_id,trainerId:row.trainer_id,traineeId:row.trainee_id,templateSnapshot:row.template_snapshot,dueDate:row.due_date,status:row.status,createdAt:row.created_at});
if(!IS_PRODUCTION){
  const trainer=await createUser({name:'Maya Adams',email:'trainer@ptrainer.local',password:'DemoTrainer1!',role:'TRAINER'}),trainee=await createUser({name:'Jordan Lee',email:'trainee@ptrainer.local',password:'DemoTrainee1!',role:'TRAINEE'});
  if(!relationships.has(`${trainer.id}:${trainee.id}`)){const relationship={trainerId:trainer.id,traineeId:trainee.id,status:'ACTIVE',createdAt:new Date().toISOString()};await query('INSERT INTO trainer_trainee_relationships(trainer_id,trainee_id,status,created_at,updated_at) VALUES($1,$2,$3,$4,$4)',[relationship.trainerId,relationship.traineeId,relationship.status,relationship.createdAt]);relationships.set(`${trainer.id}:${trainee.id}`,relationship)}
  let seedTemplate=[...workoutTemplates.values()].find(item=>item.trainerId===trainer.id&&item.name==='Upper Body Strength');if(!seedTemplate){seedTemplate={id:id('tpl'),trainerId:trainer.id,name:'Upper Body Strength',description:'A balanced upper-body strength session.',exercises:[{name:'Barbell bench press',sets:4,reps:8,restSeconds:90},{name:'Single-arm dumbbell row',sets:3,reps:10,restSeconds:75},{name:'Seated shoulder press',sets:3,reps:10,restSeconds:75},{name:'Cable triceps extension',sets:3,reps:12,restSeconds:60}],version:1,createdAt:new Date().toISOString()};await query('INSERT INTO workout_templates(id,trainer_id,name,description,version,exercises,created_at) VALUES($1,$2,$3,$4,$5,$6,$7)',[seedTemplate.id,seedTemplate.trainerId,seedTemplate.name,seedTemplate.description,seedTemplate.version,JSON.stringify(seedTemplate.exercises),seedTemplate.createdAt]);workoutTemplates.set(seedTemplate.id,seedTemplate)}
  let seedAssignment=assignments.get('assigned_demo_1');if(!seedAssignment){seedAssignment={id:'assigned_demo_1',templateId:seedTemplate.id,templateSnapshot:structuredClone(seedTemplate),trainerId:trainer.id,traineeId:trainee.id,dueDate:new Date().toISOString().slice(0,10),status:'ASSIGNED',createdAt:new Date().toISOString()};await query('INSERT INTO assigned_workouts(id,template_id,trainer_id,trainee_id,template_snapshot,due_date,status,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[seedAssignment.id,seedAssignment.templateId,seedAssignment.trainerId,seedAssignment.traineeId,JSON.stringify(seedAssignment.templateSnapshot),seedAssignment.dueDate,seedAssignment.status,seedAssignment.createdAt]);assignments.set(seedAssignment.id,seedAssignment)}
  const progressCount=await query('SELECT count(*)::int AS count FROM progress_entries WHERE trainee_id=$1',[trainee.id]);if(Number(progressCount.rows[0].count)===0){for(const [days,value]of [[56,82.4],[42,81.5],[28,80.8],[14,79.9],[0,79.2]])await query("INSERT INTO progress_entries(id,trainee_id,author_id,metric_type,value,unit,measured_at,note) VALUES($1,$2,$2,'weight',$3,'kg',$4,'')",[id('progress'),trainee.id,value,new Date(Date.now()-days*86400000).toISOString()])}
  const nutritionCount=await query('SELECT count(*)::int AS count FROM nutrition_entries WHERE trainee_id=$1',[trainee.id]);if(Number(nutritionCount.rows[0].count)===0)await query("INSERT INTO nutrition_entries(id,trainee_id,author_id,entry_date,entry_type,description,calories,protein_g,carbs_g,fat_g,water_ml) VALUES($1,$2,$2,CURRENT_DATE,'DAILY','Balanced training day',1840,132,188,58,2100)",[id('nutrition'),trainee.id]);
  const notificationCount=await query('SELECT count(*)::int AS count FROM notifications WHERE recipient_id=$1',[trainer.id]);if(Number(notificationCount.rows[0].count)===0)await query("INSERT INTO notifications(id,recipient_id,event_type,title,body) VALUES($1,$2,'PROGRESS_ADDED','New progress update','Jordan logged a new weight entry.'),($3,$2,'WORKOUT_COMPLETED','Workout completed','Jordan completed Upper Body Strength.')",[id('notification'),trainer.id,id('notification')]);
}

function securityHeaders(res,{cacheControl='no-store'}={}) {
  res.setHeader('Content-Security-Policy', "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'; object-src 'none'");
  res.setHeader('X-Content-Type-Options','nosniff'); res.setHeader('X-Frame-Options','DENY'); res.setHeader('Referrer-Policy','no-referrer');
  res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=(), payment=()'); res.setHeader('Cross-Origin-Opener-Policy','same-origin'); res.setHeader('Cross-Origin-Resource-Policy','same-origin'); res.setHeader('Cache-Control',cacheControl);
}
function json(res,status,payload){securityHeaders(res);res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify(payload))}
function textResponse(res,status,payload,contentType='text/plain; charset=utf-8'){securityHeaders(res);res.statusCode=status;res.setHeader('Content-Type',contentType);res.end(payload)}
function metricsPayload(){const uptime=(Date.now()-telemetry.startedAt)/1000,average=telemetry.requests?telemetry.totalDurationMs/telemetry.requests:0,statusLines=[...telemetry.byStatus].map(([status,count])=>`ptrainer_http_responses_total{status="${status}"} ${count}`).join('\n');return`# HELP ptrainer_up 1 when the process is running\n# TYPE ptrainer_up gauge\nptrainer_up 1\n# TYPE ptrainer_uptime_seconds gauge\nptrainer_uptime_seconds ${uptime.toFixed(3)}\n# TYPE ptrainer_http_requests_total counter\nptrainer_http_requests_total ${telemetry.requests}\n# TYPE ptrainer_http_errors_total counter\nptrainer_http_errors_total ${telemetry.errors}\n# TYPE ptrainer_http_request_duration_average_ms gauge\nptrainer_http_request_duration_average_ms ${average.toFixed(3)}\n${statusLines}\n`}
function parseCookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').map(v=>v.trim()).filter(Boolean).map(v=>{const i=v.indexOf('=');return[v.slice(0,i),decodeURIComponent(v.slice(i+1))]}))}
function setSessionCookie(res,sid,maxAge=3600){res.setHeader('Set-Cookie',`${COOKIE}=${sid}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${maxAge}${IS_PRODUCTION?'; Secure':''}`)}
function getSession(req,res){
  const sid=parseCookies(req)[COOKIE];let session=sid&&sessions.get(sid);
  if(session&&Date.now()-session.lastSeen>SESSION_TTL){sessions.delete(sid);session=null}
  if(!session){const newSid=randomBytes(32).toString('base64url');session={sid:newSid,userId:null,csrf:randomBytes(32).toString('base64url'),lastSeen:Date.now()};sessions.set(newSid,session);setSessionCookie(res,newSid)}
  session.lastSeen=Date.now();return session;
}
function rotateSession(res,oldSession,userId=null){sessions.delete(oldSession.sid);const sid=randomBytes(32).toString('base64url');const session={sid,userId,csrf:randomBytes(32).toString('base64url'),lastSeen:Date.now()};sessions.set(sid,session);setSessionCookie(res,sid);return session}
function sessionUser(session){return session.userId?users.get(session.userId):null}
function authenticated(res,session){const user=sessionUser(session);if(!user){json(res,401,{error:{code:'AUTH_REQUIRED',message:'Please sign in.'}});return null}return user}
function requireRole(res,user,role){if(user.role!==role){json(res,403,{error:{code:'FORBIDDEN',message:`${role.toLowerCase()} access required.`}});return false}return true}
function sameToken(a='',b=''){const left=Buffer.from(String(a));const right=Buffer.from(String(b));return left.length===right.length&&timingSafeEqual(left,right)}
function mutationAllowed(req,res,session){const origin=req.headers.origin;if(origin&&origin!==APP_ORIGIN){json(res,403,{error:{code:'ORIGIN_REJECTED',message:'Request origin is not allowed.'}});return false}if(!sameToken(req.headers['x-csrf-token'],session.csrf)){json(res,403,{error:{code:'CSRF_INVALID',message:'Security token is missing or invalid.'}});return false}if(!(req.headers['content-type']||'').startsWith('application/json')){json(res,415,{error:{code:'CONTENT_TYPE_INVALID',message:'Use application/json.'}});return false}return true}
async function readJson(req,res,maxBytes=32768){let size=0;const chunks=[];for await(const chunk of req){size+=chunk.length;if(size>maxBytes){json(res,413,{error:{code:'PAYLOAD_TOO_LARGE',message:'Request is too large.'}});return null}chunks.push(chunk)}try{return JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}')}catch{json(res,400,{error:{code:'JSON_INVALID',message:'Malformed JSON.'}});return null}}
function rateLimit(key,limit,windowMs){const now=Date.now();const active=(rateBuckets.get(key)||[]).filter(t=>now-t<windowMs);if(active.length>=limit)return false;active.push(now);rateBuckets.set(key,active);return true}
async function audit(actorId,action,entityType,entityId=null,metadata={}){try{await query('INSERT INTO audit_events(id,actor_id,action,entity_type,entity_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[id('audit'),actorId,action,entityType,entityId,JSON.stringify(metadata)])}catch(error){console.error('audit_write_failed',{action,entityType,message:error.message})}}
async function trainerDashboard(user){
  const traineeIds=[...relationships.values()].filter(r=>r.trainerId===user.id&&r.status==='ACTIVE').map(r=>r.traineeId),trainerAssignments=[...assignments.values()].filter(a=>a.trainerId===user.id&&a.status!=='ARCHIVED'),completed=trainerAssignments.filter(a=>a.status==='COMPLETED').length;
  const progress=traineeIds.length?await query("SELECT count(*)::int AS count FROM progress_entries WHERE trainee_id = ANY($1) AND measured_at >= now() - interval '7 days'",[traineeIds]):{rows:[{count:0}]};
  const clients=traineeIds.map(userId=>{const client=publicUser(users.get(userId)),clientAssignments=trainerAssignments.filter(a=>a.traineeId===userId),clientCompleted=clientAssignments.filter(a=>a.status==='COMPLETED').length;return{...client,assignedCount:clientAssignments.length,completedCount:clientCompleted,completionRate:clientAssignments.length?Math.round(clientCompleted/clientAssignments.length*100):0,lastWorkout:clientAssignments.sort((a,b)=>String(b.dueDate).localeCompare(String(a.dueDate)))[0]?.templateSnapshot?.name||'No program assigned'}});
  const overdue=trainerAssignments.filter(a=>a.status==='ASSIGNED'&&a.dueDate&&new Date(a.dueDate)<new Date(new Date().toISOString().slice(0,10)));
  return{kind:'TRAINER',activeClients:traineeIds.length,clients,workoutsCompleted:completed,assignedCount:trainerAssignments.length,completionRate:trainerAssignments.length?Math.round(completed/trainerAssignments.length*100):0,progressUpdates:Number(progress.rows[0]?.count||0),attentionCount:overdue.length,attentionItems:overdue.slice(0,5).map(a=>({id:a.id,trainee:publicUser(users.get(a.traineeId)),name:a.templateSnapshot.name,dueDate:a.dueDate})),upcoming:trainerAssignments.filter(a=>!['COMPLETED','SKIPPED'].includes(a.status)).sort((a,b)=>String(a.dueDate||'9999').localeCompare(String(b.dueDate||'9999'))).slice(0,6).map(a=>({id:a.id,trainee:publicUser(users.get(a.traineeId)),name:a.templateSnapshot.name,dueDate:a.dueDate,status:a.status}))};
}
async function traineeDashboard(user){const active=[...assignments.values()].filter(a=>a.traineeId===user.id&&a.status!=='ARCHIVED').sort((a,b)=>String(a.dueDate).localeCompare(String(b.dueDate))),completed=active.filter(a=>a.status==='COMPLETED').length,relationship=[...relationships.values()].find(item=>item.traineeId===user.id&&item.status==='ACTIVE'),trainerUser=relationship&&users.get(relationship.trainerId);return{kind:'TRAINEE',todayWorkout:active[0]?{id:active[0].id,name:active[0].templateSnapshot.name,exerciseCount:active[0].templateSnapshot.exercises.length,status:active[0].status}:null,currentStreak:completed,weeklyCompletion:active.length?Math.round(completed/active.length*100):0,completedCount:completed,assignedCount:active.length,trainerName:trainerUser?.name||null}}
function accessibleTrainee(user,requestedId){const traineeId=user.role==='TRAINEE'?user.id:requestedId;if(!traineeId)return null;if(user.role==='TRAINEE')return traineeId;const relationship=relationships.get(`${user.id}:${traineeId}`);return relationship?.status==='ACTIVE'?traineeId:null}
function activeRelationship(user,requestedTraineeId){return user.role==='TRAINER'?[...relationships.values()].find(item=>item.trainerId===user.id&&item.status==='ACTIVE'&&(!requestedTraineeId||item.traineeId===requestedTraineeId)):[...relationships.values()].find(item=>item.traineeId===user.id&&item.status==='ACTIVE')}

async function authApi(req,res,url,session){
  if(req.method==='POST'&&url.pathname==='/api/auth/register'){
    if(!mutationAllowed(req,res,session))return true;if(!rateLimit(`register:${req.socket.remoteAddress}`,5,3600000)){json(res,429,{error:{code:'RATE_LIMITED',message:'Too many registration attempts.'}});return true}
    const body=await readJson(req,res);if(!body)return true;const email=cleanEmail(body.email),role=body.role;
    if(!validName(body.name)){json(res,422,{error:{code:'NAME_INVALID',message:'Name must be 2–80 characters.'}});return true}if(!validEmail(email)){json(res,422,{error:{code:'EMAIL_INVALID',message:'Enter a valid email address.'}});return true}if(!validPassword(body.password)){json(res,422,{error:{code:'PASSWORD_WEAK',message:'Use 10+ characters with upper/lowercase, number, and symbol.'}});return true}if(!['TRAINER','TRAINEE'].includes(role)){json(res,422,{error:{code:'ROLE_INVALID',message:'Choose trainer or trainee.'}});return true}if(usersByEmail.has(email)){json(res,409,{error:{code:'EMAIL_EXISTS',message:'An account already exists for this email.'}});return true}
    const user=await createUser({name:body.name,email,password:body.password,role});const next=rotateSession(res,session,user.id);json(res,201,{user:publicUser(user),csrfToken:next.csrf});return true;
  }
  if(req.method==='POST'&&url.pathname==='/api/auth/login'){
    if(!mutationAllowed(req,res,session))return true;const body=await readJson(req,res);if(!body)return true;const email=cleanEmail(body.email);const bucket=`login:${req.socket.remoteAddress}:${email}`;
    if(!rateLimit(bucket,8,15*60*1000)){json(res,429,{error:{code:'RATE_LIMITED',message:'Too many sign-in attempts. Try again later.'}});return true}const userId=usersByEmail.get(email),user=userId&&users.get(userId);const correct=user&&await verifyPassword(String(body.password||''),user.passwordHash);
    if(!correct||user.status!=='ACTIVE'){await new Promise(resolve=>setTimeout(resolve,180));json(res,401,{error:{code:'CREDENTIALS_INVALID',message:'Email or password is incorrect.'}});return true}const next=rotateSession(res,session,user.id);json(res,200,{user:publicUser(user),csrfToken:next.csrf});return true;
  }
  if(req.method==='POST'&&url.pathname==='/api/auth/forgot-password'){
    if(!mutationAllowed(req,res,session))return true;const body=await readJson(req,res);if(!body)return true;const email=cleanEmail(body.email);
    if(!rateLimit(`password-reset:${req.socket.remoteAddress}:${email}`,5,3600000)){json(res,429,{error:{code:'RATE_LIMITED',message:'Too many reset requests. Try again later.'}});return true}
    const userId=usersByEmail.get(email);let demoResetToken=null;
    if(userId){const rawToken=randomBytes(32).toString('base64url');const tokenHash=Buffer.from(await scrypt(rawToken,'ptrainer-reset-v1',32)).toString('base64url');const reset={userId,expiresAt:Date.now()+15*60*1000,used:false};passwordResets.set(tokenHash,reset);await query('INSERT INTO password_reset_tokens(token_hash,user_id,expires_at) VALUES($1,$2,$3) ON CONFLICT(token_hash) DO NOTHING',[tokenHash,userId,new Date(reset.expiresAt).toISOString()]);demoResetToken=rawToken}
    json(res,202,{message:'If the account exists, reset instructions have been created.',...(!IS_PRODUCTION&&demoResetToken?{demoResetToken}:{})});return true;
  }
  if(req.method==='POST'&&url.pathname==='/api/auth/reset-password'){
    if(!mutationAllowed(req,res,session))return true;const body=await readJson(req,res);if(!body)return true;if(!validPassword(body.password)){json(res,422,{error:{code:'PASSWORD_WEAK',message:'Use 10+ characters with upper/lowercase, number, and symbol.'}});return true}
    const rawToken=typeof body.token==='string'?body.token:'';const tokenHash=Buffer.from(await scrypt(rawToken,'ptrainer-reset-v1',32)).toString('base64url');let reset=passwordResets.get(tokenHash);if(!reset){const stored=await query('SELECT user_id,expires_at,used_at FROM password_reset_tokens WHERE token_hash=$1',[tokenHash]);if(stored.rowCount)reset={userId:stored.rows[0].user_id,expiresAt:new Date(stored.rows[0].expires_at).getTime(),used:Boolean(stored.rows[0].used_at)}}
    if(!reset||reset.used||reset.expiresAt<Date.now()){json(res,400,{error:{code:'RESET_TOKEN_INVALID',message:'Reset link is invalid or expired.'}});return true}
    const user=users.get(reset.userId);reset.used=true;user.passwordHash=await hashPassword(body.password);await query('UPDATE users SET password_hash=$1,updated_at=now() WHERE id=$2',[user.passwordHash,user.id]);await query('UPDATE password_reset_tokens SET used_at=now() WHERE token_hash=$1',[tokenHash]);for(const [sid,item]of sessions)if(item.userId===user.id)sessions.delete(sid);const next=rotateSession(res,session,null);json(res,200,{message:'Password updated. Sign in with your new password.',csrfToken:next.csrf});return true;
  }
  if(req.method==='POST'&&url.pathname==='/api/auth/logout'){if(!mutationAllowed(req,res,session))return true;sessions.delete(session.sid);setSessionCookie(res,'',0);json(res,200,{ok:true});return true}
  return false;
}

async function api(req,res,url){
  let session=getSession(req,res);
  if(req.method==='GET'&&url.pathname==='/api/session'){const user=sessionUser(session);return json(res,200,{authenticated:Boolean(user),user:user?publicUser(user):null,csrfToken:session.csrf,demoMode:!IS_PRODUCTION})}
  if(await authApi(req,res,url,session))return;
  const user=authenticated(res,session);if(!user)return;
  if(req.method==='GET'&&url.pathname==='/api/me'){
    const profileResult=await query('SELECT bio,goals,specialties,preferred_units,timezone,updated_at FROM user_profiles WHERE user_id=$1',[user.id]);
    return json(res,200,{user:publicUser(user),profile:profileResult.rows[0]||{bio:'',goals:'',specialties:'',preferred_units:'METRIC',timezone:'America/Toronto'}});
  }
  if(req.method==='PATCH'&&url.pathname==='/api/me/profile'){
    if(!mutationAllowed(req,res,session))return;const body=await readJson(req,res);if(!body)return;const name=String(body.name||'').trim(),bio=String(body.bio||'').trim(),goals=String(body.goals||'').trim(),specialties=String(body.specialties||'').trim(),preferredUnits=String(body.preferredUnits||'METRIC').toUpperCase(),timezone=String(body.timezone||'America/Toronto').trim();
    if(!validName(name)||bio.length>1000||goals.length>1000||specialties.length>500||!['METRIC','IMPERIAL'].includes(preferredUnits)||timezone.length<3||timezone.length>80)return json(res,422,{error:{code:'PROFILE_INVALID',message:'Profile fields are invalid or too long.'}});
    user.name=name;await query('UPDATE users SET name=$1,updated_at=now() WHERE id=$2',[name,user.id]);await query('INSERT INTO user_profiles(user_id,bio,goals,specialties,preferred_units,timezone) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(user_id) DO UPDATE SET bio=$2,goals=$3,specialties=$4,preferred_units=$5,timezone=$6,updated_at=now()',[user.id,bio,goals,specialties,preferredUnits,timezone]);await audit(user.id,'PROFILE_UPDATED','user',user.id);return json(res,200,{user:publicUser(user),profile:{bio,goals,specialties,preferred_units:preferredUnits,timezone}});
  }
  if(req.method==='GET'&&url.pathname==='/api/me/export'){
    const [profile,connections,workouts,logs,progress,nutrition,messages]=await Promise.all([query('SELECT bio,goals,specialties,preferred_units,timezone,updated_at FROM user_profiles WHERE user_id=$1',[user.id]),query('SELECT trainer_id,trainee_id,status,created_at,updated_at FROM trainer_trainee_relationships WHERE trainer_id=$1 OR trainee_id=$1',[user.id]),query('SELECT id,template_snapshot,due_date,status,created_at FROM assigned_workouts WHERE trainer_id=$1 OR trainee_id=$1',[user.id]),query('SELECT id,assigned_workout_id,exercises,completed_count,created_at FROM workout_logs WHERE author_id=$1',[user.id]),query('SELECT id,metric_type,value,unit,measured_at,note,created_at FROM progress_entries WHERE trainee_id=$1',[user.id]),query('SELECT id,entry_date,entry_type,description,calories,protein_g,carbs_g,fat_g,water_ml,created_at FROM nutrition_entries WHERE trainee_id=$1',[user.id]),query('SELECT id,sender_id,body,created_at FROM messages WHERE sender_id=$1',[user.id])]);
    await audit(user.id,'PERSONAL_DATA_EXPORTED','user',user.id);return json(res,200,{exportedAt:new Date().toISOString(),user:publicUser(user),profile:profile.rows[0]||null,relationships:connections.rows,assignedWorkouts:workouts.rows,authoredWorkoutLogs:logs.rows,progressEntries:progress.rows,nutritionEntries:nutrition.rows,authoredMessages:messages.rows});
  }
  if(req.method==='GET'&&url.pathname==='/api/me/audit-events'){const result=await query('SELECT action,entity_type,entity_id,metadata,created_at FROM audit_events WHERE actor_id=$1 ORDER BY created_at DESC LIMIT 50',[user.id]);return json(res,200,{events:result.rows})}
  if(req.method==='DELETE'&&url.pathname==='/api/me/account'){
    if(!mutationAllowed(req,res,session))return;const body=await readJson(req,res);if(!body)return;if(body.confirmation!=='DELETE PTRAINER ACCOUNT')return json(res,422,{error:{code:'DELETION_CONFIRMATION_INVALID',message:'Enter the exact account deletion confirmation.'}});const correct=await verifyPassword(String(body.password||''),user.passwordHash);if(!correct)return json(res,401,{error:{code:'CREDENTIALS_INVALID',message:'Password is incorrect.'}});const anonymousEmail=`deleted+${tokenDigest(user.id).slice(0,20).toLowerCase()}@ptrainer.invalid`,randomPassword=await hashPassword(randomBytes(32).toString('base64url'));await transaction(async tx=>{await tx('INSERT INTO audit_events(id,actor_id,action,entity_type,entity_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[id('audit'),user.id,'ACCOUNT_DELETED','user',user.id,'{}']);await tx("UPDATE users SET email=$1,password_hash=$2,name='Deleted user',status='DELETED',updated_at=now() WHERE id=$3",[anonymousEmail,randomPassword,user.id]);await tx('DELETE FROM user_profiles WHERE user_id=$1',[user.id])});usersByEmail.delete(user.email);user.email=anonymousEmail;user.name='Deleted user';user.status='DELETED';for(const [sid,item]of sessions)if(item.userId===user.id)sessions.delete(sid);setSessionCookie(res,'',0);return json(res,200,{deleted:true});
  }
  if(req.method==='GET'&&url.pathname==='/api/dashboard')return json(res,200,await (user.role==='TRAINER'?trainerDashboard(user):traineeDashboard(user)));
  if(req.method==='GET'&&url.pathname==='/api/exercises'){
    if(!requireRole(res,user,'TRAINER'))return;const search=String(url.searchParams.get('q')||'').trim().toLocaleLowerCase().slice(0,100),limit=Math.min(250,Math.max(1,Number(url.searchParams.get('limit'))||60)),matches=exerciseCatalog.filter(item=>!search||item.name.toLocaleLowerCase().includes(search)||item.muscleGroup.toLocaleLowerCase().includes(search)||item.equipment.toLocaleLowerCase().includes(search));return json(res,200,{exercises:matches.slice(0,limit),total:matches.length,catalogTotal:exerciseCatalog.length,customNamesAllowed:true});
  }
  if(req.method==='GET'&&url.pathname==='/api/workout-templates'){if(!requireRole(res,user,'TRAINER'))return;return json(res,200,{templates:[...workoutTemplates.values()].filter(t=>t.trainerId===user.id)})}
  if(req.method==='POST'&&url.pathname==='/api/workout-templates'){
    if(!mutationAllowed(req,res,session)||!requireRole(res,user,'TRAINER'))return;const body=await readJson(req,res);if(!body)return;const name=typeof body.name==='string'?body.name.trim():'';
    if(name.length<3||name.length>100||!Array.isArray(body.exercises)||body.exercises.length<1||body.exercises.length>30)return json(res,422,{error:{code:'TEMPLATE_INVALID',message:'Add a name and 1–30 valid exercises.'}});
    const exercises=body.exercises.map(x=>({name:String(x.name||'').trim().slice(0,100),sets:Math.min(20,Math.max(1,Number(x.sets)||1)),reps:Math.min(1000,Math.max(1,Number(x.reps)||1)),restSeconds:Math.min(900,Math.max(0,Number(x.restSeconds)||0))}));if(exercises.some(x=>x.name.length<2))return json(res,422,{error:{code:'EXERCISE_INVALID',message:'Every exercise needs a valid name.'}});
    const template={id:id('tpl'),trainerId:user.id,name,description:String(body.description||'').trim().slice(0,500),exercises,version:1,createdAt:new Date().toISOString()};await query('INSERT INTO workout_templates(id,trainer_id,name,description,version,exercises,created_at) VALUES($1,$2,$3,$4,$5,$6,$7)',[template.id,template.trainerId,template.name,template.description,template.version,JSON.stringify(template.exercises),template.createdAt]);workoutTemplates.set(template.id,template);await audit(user.id,'WORKOUT_TEMPLATE_CREATED','workout_template',template.id);return json(res,201,{template});
  }
  if(req.method==='POST'&&url.pathname==='/api/assigned-workouts'){
    if(!mutationAllowed(req,res,session)||!requireRole(res,user,'TRAINER'))return;const body=await readJson(req,res);if(!body)return;const template=workoutTemplates.get(body.templateId),relationship=relationships.get(`${user.id}:${body.traineeId}`);
    if(!template||template.trainerId!==user.id||!relationship||relationship.status!=='ACTIVE')return json(res,403,{error:{code:'ASSIGNMENT_FORBIDDEN',message:'Template or trainee access is invalid.'}});const assignment={id:id('assigned'),templateId:template.id,templateSnapshot:structuredClone(template),trainerId:user.id,traineeId:body.traineeId,dueDate:String(body.dueDate||'').slice(0,10),status:'ASSIGNED',createdAt:new Date().toISOString()};await query('INSERT INTO assigned_workouts(id,template_id,trainer_id,trainee_id,template_snapshot,due_date,status,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[assignment.id,assignment.templateId,assignment.trainerId,assignment.traineeId,JSON.stringify(assignment.templateSnapshot),assignment.dueDate||null,assignment.status,assignment.createdAt]);assignments.set(assignment.id,assignment);await audit(user.id,'WORKOUT_ASSIGNED','assigned_workout',assignment.id,{traineeId:assignment.traineeId});return json(res,201,{assignment});
  }
  if(req.method==='POST'&&url.pathname==='/api/assigned-workouts/custom'){
    if(!mutationAllowed(req,res,session)||!requireRole(res,user,'TRAINER'))return;const body=await readJson(req,res);if(!body)return;const workout=normalizeWorkoutInput(body),relationship=relationships.get(`${user.id}:${body.traineeId}`);if(!workout)return json(res,422,{error:{code:'WORKOUT_INVALID',message:'Add a valid name, date, and 1–30 exercises.'}});if(!relationship||relationship.status!=='ACTIVE')return json(res,403,{error:{code:'ASSIGNMENT_FORBIDDEN',message:'An active coaching relationship is required.'}});const createdAt=new Date().toISOString(),template={id:id('tpl'),trainerId:user.id,name:workout.name,description:workout.description,exercises:workout.exercises,version:1,createdAt},assignment={id:id('assigned'),templateId:null,templateSnapshot:null,trainerId:user.id,traineeId:body.traineeId,dueDate:workout.dueDate,status:'ASSIGNED',createdAt};assignment.templateId=template.id;assignment.templateSnapshot=structuredClone(template);await transaction(async tx=>{await tx('INSERT INTO workout_templates(id,trainer_id,name,description,version,exercises,created_at) VALUES($1,$2,$3,$4,$5,$6,$7)',[template.id,template.trainerId,template.name,template.description,template.version,JSON.stringify(template.exercises),template.createdAt]);await tx('INSERT INTO assigned_workouts(id,template_id,trainer_id,trainee_id,template_snapshot,due_date,status,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[assignment.id,assignment.templateId,assignment.trainerId,assignment.traineeId,JSON.stringify(assignment.templateSnapshot),assignment.dueDate||null,assignment.status,assignment.createdAt]);await tx("INSERT INTO notifications(id,recipient_id,event_type,title,body) VALUES($1,$2,'WORKOUT_ASSIGNED',$3,$4)",[id('notification'),assignment.traineeId,'New workout assigned',`${assignment.templateSnapshot.name}${assignment.dueDate?` · ${assignment.dueDate}`:''}`])});workoutTemplates.set(template.id,template);assignments.set(assignment.id,assignment);await audit(user.id,'WORKOUT_ASSIGNED','assigned_workout',assignment.id,{traineeId:assignment.traineeId,custom:true});return json(res,201,{assignment});
  }
  if(req.method==='GET'&&url.pathname==='/api/assigned-workouts'){const visible=[...assignments.values()].filter(a=>user.role==='TRAINER'?a.trainerId===user.id:a.traineeId===user.id);return json(res,200,{assignments:visible})}
  const assignmentEdit=url.pathname.match(/^\/api\/assigned-workouts\/([A-Za-z0-9_-]{1,64})$/);
  if(req.method==='PATCH'&&assignmentEdit){
    if(!mutationAllowed(req,res,session)||!requireRole(res,user,'TRAINER'))return;const assignment=assignments.get(assignmentEdit[1]);if(!assignment||assignment.trainerId!==user.id)return json(res,404,{error:{code:'WORKOUT_NOT_FOUND',message:'Assigned workout not found.'}});const relationship=relationships.get(`${user.id}:${assignment.traineeId}`);if(!relationship||relationship.status!=='ACTIVE')return json(res,403,{error:{code:'WORKOUT_EDIT_FORBIDDEN',message:'An active coaching relationship is required.'}});if(assignment.status!=='ASSIGNED')return json(res,409,{error:{code:'WORKOUT_LOCKED',message:'A workout cannot be edited after logging has started.'}});const body=await readJson(req,res);if(!body)return;const workout=normalizeWorkoutInput(body);if(!workout)return json(res,422,{error:{code:'WORKOUT_INVALID',message:'Add a valid name, date, and 1–30 exercises.'}});assignment.templateSnapshot={...assignment.templateSnapshot,name:workout.name,description:workout.description,exercises:workout.exercises,version:Number(assignment.templateSnapshot.version||1)+1};assignment.dueDate=workout.dueDate;await transaction(async tx=>{await tx('UPDATE assigned_workouts SET template_snapshot=$1,due_date=$2 WHERE id=$3 AND trainer_id=$4 AND status=\'ASSIGNED\'',[JSON.stringify(assignment.templateSnapshot),assignment.dueDate||null,assignment.id,user.id]);await tx("INSERT INTO notifications(id,recipient_id,event_type,title,body) VALUES($1,$2,'WORKOUT_UPDATED',$3,$4)",[id('notification'),assignment.traineeId,'Workout updated',assignment.templateSnapshot.name])});await audit(user.id,'ASSIGNED_WORKOUT_UPDATED','assigned_workout',assignment.id,{traineeId:assignment.traineeId,version:assignment.templateSnapshot.version});return json(res,200,{assignment});
  }
  if(req.method==='POST'&&url.pathname==='/api/invitations'){
    if(!mutationAllowed(req,res,session)||!requireRole(res,user,'TRAINER'))return;if(!rateLimit(`invite:${user.id}`,10,3600000))return json(res,429,{error:{code:'RATE_LIMITED',message:'Too many invitations. Try again later.'}});const body=await readJson(req,res);if(!body)return;const email=cleanEmail(body.email),note=typeof body.note==='string'?body.note.trim():'';
    if(!validEmail(email))return json(res,422,{error:{code:'EMAIL_INVALID',message:'Enter a valid email address.'}});if(note.length>500)return json(res,422,{error:{code:'NOTE_TOO_LONG',message:'Note must be 500 characters or fewer.'}});const pendingInvite=await query("SELECT 1 FROM invitations WHERE trainer_id=$1 AND email=$2 AND status='PENDING'",[user.id,email]);if([...invitations.values()].some(i=>i.email===email&&i.trainerId===user.id&&i.status==='PENDING')||pendingInvite.rowCount)return json(res,409,{error:{code:'INVITE_EXISTS',message:'A pending invitation already exists.'}});
    const token=randomBytes(24).toString('base64url'),invite={id:id('inv'),token,email,note,status:'PENDING',trainerId:user.id,expiresAt:Date.now()+7*86400000,createdAt:new Date().toISOString()};await query('INSERT INTO invitations(id,trainer_id,email,token_hash,note,status,expires_at,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[invite.id,invite.trainerId,invite.email,tokenDigest(token),invite.note,invite.status,new Date(invite.expiresAt).toISOString(),invite.createdAt]);invitations.set(token,invite);return json(res,201,{invitation:{id:invite.id,email,status:invite.status,inviteCode:token,expiresAt:new Date(invite.expiresAt).toISOString()}});
  }
  const accept=url.pathname.match(/^\/api\/invitations\/([A-Za-z0-9_-]{20,60})\/accept$/);
  if(req.method==='POST'&&accept){if(!mutationAllowed(req,res,session)||!requireRole(res,user,'TRAINEE'))return;let invite=invitations.get(accept[1]);if(!invite){const found=await query('SELECT id,trainer_id,email,status,expires_at FROM invitations WHERE token_hash=$1',[tokenDigest(accept[1])]);if(found.rowCount)invite={id:found.rows[0].id,trainerId:found.rows[0].trainer_id,email:found.rows[0].email,status:found.rows[0].status,expiresAt:new Date(found.rows[0].expires_at).getTime()}}if(!invite||invite.status!=='PENDING'||invite.expiresAt<Date.now()||invite.email!==user.email)return json(res,403,{error:{code:'INVITE_INVALID',message:'Invitation is invalid, expired, or belongs to another email.'}});const relationship={trainerId:invite.trainerId,traineeId:user.id,status:'ACTIVE',createdAt:new Date().toISOString()};await transaction(async tx=>{await tx("UPDATE invitations SET status='ACCEPTED' WHERE id=$1 AND status='PENDING'",[invite.id]);await tx("INSERT INTO trainer_trainee_relationships(trainer_id,trainee_id,status,created_at,updated_at) VALUES($1,$2,'ACTIVE',$3,$3) ON CONFLICT(trainer_id,trainee_id) DO UPDATE SET status='ACTIVE',updated_at=$3",[relationship.trainerId,relationship.traineeId,relationship.createdAt])});invite.status='ACCEPTED';relationships.set(`${invite.trainerId}:${user.id}`,relationship);await audit(user.id,'INVITATION_ACCEPTED','relationship',`${relationship.trainerId}:${relationship.traineeId}`);return json(res,200,{relationship:{status:'ACTIVE'}})}
  if(req.method==='GET'&&url.pathname==='/api/relationships'){
    const visible=[...relationships.values()].filter(item=>user.role==='TRAINER'?item.trainerId===user.id:item.traineeId===user.id).map(item=>({...item,trainer:publicUser(users.get(item.trainerId)),trainee:publicUser(users.get(item.traineeId))}));
    return json(res,200,{relationships:visible});
  }
  const relationshipStatus=url.pathname.match(/^\/api\/relationships\/([A-Za-z0-9_-]{1,64})\/([A-Za-z0-9_-]{1,64})$/);
  if(req.method==='PATCH'&&relationshipStatus){
    if(!mutationAllowed(req,res,session))return;const [trainerId,traineeId]=relationshipStatus.slice(1),relationship=relationships.get(`${trainerId}:${traineeId}`);if(!relationship||(user.id!==trainerId&&user.id!==traineeId))return json(res,404,{error:{code:'RELATIONSHIP_NOT_FOUND',message:'Coaching relationship not found.'}});const body=await readJson(req,res);if(!body)return;const nextStatus=String(body.status||'').toUpperCase();if(!['ACTIVE','PAUSED','ARCHIVED','REVOKED'].includes(nextStatus))return json(res,422,{error:{code:'RELATIONSHIP_STATUS_INVALID',message:'Choose a valid relationship status.'}});if(nextStatus==='ACTIVE'&&relationship.status!=='PAUSED')return json(res,409,{error:{code:'RELATIONSHIP_REACTIVATION_INVALID',message:'Only a paused relationship can be reactivated.'}});relationship.status=nextStatus;await query('UPDATE trainer_trainee_relationships SET status=$1,updated_at=now() WHERE trainer_id=$2 AND trainee_id=$3',[nextStatus,trainerId,traineeId]);return json(res,200,{relationship});
  }
  const logMatch=url.pathname.match(/^\/api\/assigned-workouts\/([A-Za-z0-9_-]{1,64})\/logs$/);
  if(req.method==='POST'&&logMatch){
    if(!mutationAllowed(req,res,session))return;const assignment=assignments.get(logMatch[1]);if(!assignment||(user.role==='TRAINEE'?assignment.traineeId!==user.id:assignment.trainerId!==user.id))return json(res,403,{error:{code:'WORKOUT_FORBIDDEN',message:'You cannot log this workout.'}});const key=req.headers['idempotency-key'];if(typeof key!=='string'||!/^[A-Za-z0-9_-]{16,100}$/.test(key))return json(res,400,{error:{code:'IDEMPOTENCY_KEY_REQUIRED',message:'A valid idempotency key is required.'}});const cacheKey=`${user.id}:${key}`;if(workoutSaves.has(cacheKey))return json(res,200,workoutSaves.get(cacheKey));const storedLog=await query('SELECT id,assigned_workout_id,completed_count,created_at FROM workout_logs WHERE author_id=$1 AND idempotency_key=$2',[user.id,key]);if(storedLog.rowCount){const row=storedLog.rows[0];return json(res,200,{log:{id:row.id,assignedWorkoutId:row.assigned_workout_id,completedCount:row.completed_count,savedAt:row.created_at}})}const body=await readJson(req,res);if(!body)return;if(!Array.isArray(body.exercises)||body.exercises.length>50)return json(res,422,{error:{code:'WORKOUT_INVALID',message:'Workout exercise data is invalid.'}});const result={log:{id:id('log'),assignedWorkoutId:assignment.id,completedCount:body.exercises.filter(x=>Boolean(x.completed)).length,savedAt:new Date().toISOString()}},nextStatus=result.log.completedCount===assignment.templateSnapshot.exercises.length?'COMPLETED':'IN_PROGRESS';await transaction(async tx=>{await tx('INSERT INTO workout_logs(id,assigned_workout_id,author_id,idempotency_key,exercises,completed_count,created_at) VALUES($1,$2,$3,$4,$5,$6,$7)',[result.log.id,assignment.id,user.id,key,JSON.stringify(body.exercises),result.log.completedCount,result.log.savedAt]);await tx('UPDATE assigned_workouts SET status=$1 WHERE id=$2',[nextStatus,assignment.id])});assignment.status=nextStatus;await audit(user.id,'WORKOUT_LOGGED','workout_log',result.log.id,{assignmentId:assignment.id,completedCount:result.log.completedCount});workoutSaves.set(cacheKey,result);return json(res,201,result);
  }
  if(req.method==='GET'&&url.pathname==='/api/progress-entries'){const traineeId=accessibleTrainee(user,url.searchParams.get('traineeId'));if(!traineeId)return json(res,403,{error:{code:'PROGRESS_FORBIDDEN',message:'Progress access is not allowed.'}});const metric=(url.searchParams.get('metric')||'weight').slice(0,50);const result=await query('SELECT id,metric_type,value::float,unit,measured_at,note,author_id FROM progress_entries WHERE trainee_id=$1 AND metric_type=$2 ORDER BY measured_at ASC LIMIT 100',[traineeId,metric]);return json(res,200,{entries:result.rows})}
  if(req.method==='POST'&&url.pathname==='/api/progress-entries'){if(!mutationAllowed(req,res,session))return;const body=await readJson(req,res);if(!body)return;const traineeId=accessibleTrainee(user,body.traineeId);if(!traineeId)return json(res,403,{error:{code:'PROGRESS_FORBIDDEN',message:'Progress access is not allowed.'}});const metric=String(body.metricType||'').trim().toLowerCase(),unit=String(body.unit||'').trim().toLowerCase(),value=Number(body.value),measuredAt=new Date(body.measuredAt||Date.now());if(!/^[a-z][a-z0-9_]{1,49}$/.test(metric)||!['kg','lb','cm','percent'].includes(unit)||!Number.isFinite(value)||value<0||value>10000||Number.isNaN(measuredAt.getTime()))return json(res,422,{error:{code:'PROGRESS_INVALID',message:'Progress value, metric, date, or unit is invalid.'}});const entry={id:id('progress'),metric_type:metric,value,unit,measured_at:measuredAt.toISOString(),note:String(body.note||'').trim().slice(0,500),author_id:user.id};await query('INSERT INTO progress_entries(id,trainee_id,author_id,metric_type,value,unit,measured_at,note) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[entry.id,traineeId,user.id,metric,value,unit,entry.measured_at,entry.note]);return json(res,201,{entry})}
  if(req.method==='GET'&&url.pathname==='/api/nutrition-entries'){const traineeId=accessibleTrainee(user,url.searchParams.get('traineeId'));if(!traineeId)return json(res,403,{error:{code:'NUTRITION_FORBIDDEN',message:'Nutrition access is not allowed.'}});const result=await query('SELECT id,entry_date,entry_type,description,calories,protein_g::float,carbs_g::float,fat_g::float,water_ml,created_at FROM nutrition_entries WHERE trainee_id=$1 ORDER BY entry_date DESC,created_at DESC LIMIT 60',[traineeId]);return json(res,200,{entries:result.rows})}
  if(req.method==='POST'&&url.pathname==='/api/nutrition-entries'){if(!mutationAllowed(req,res,session))return;const body=await readJson(req,res);if(!body)return;const traineeId=accessibleTrainee(user,body.traineeId);if(!traineeId)return json(res,403,{error:{code:'NUTRITION_FORBIDDEN',message:'Nutrition access is not allowed.'}});const numberOrNull=value=>value===''||value==null?null:Number(value);const values=[body.calories,body.proteinG,body.carbsG,body.fatG,body.waterMl].map(numberOrNull);if(values.some(value=>value!==null&&(!Number.isFinite(value)||value<0||value>100000)))return json(res,422,{error:{code:'NUTRITION_INVALID',message:'Nutrition values must be valid nonnegative numbers.'}});const entry={id:id('nutrition'),entryDate:String(body.entryDate||new Date().toISOString().slice(0,10)).slice(0,10),entryType:String(body.entryType||'DAILY').slice(0,30),description:String(body.description||'').trim().slice(0,1000)};await query('INSERT INTO nutrition_entries(id,trainee_id,author_id,entry_date,entry_type,description,calories,protein_g,carbs_g,fat_g,water_ml) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[entry.id,traineeId,user.id,entry.entryDate,entry.entryType,entry.description,...values]);return json(res,201,{entry})}
  if(req.method==='GET'&&url.pathname==='/api/notifications'){const result=await query('SELECT id,event_type,title,body,read_at,created_at FROM notifications WHERE recipient_id=$1 ORDER BY created_at DESC LIMIT 50',[user.id]);return json(res,200,{notifications:result.rows,unreadCount:result.rows.filter(item=>!item.read_at).length})}
  const notificationRead=url.pathname.match(/^\/api\/notifications\/([A-Za-z0-9_-]{1,64})\/read$/);if(req.method==='POST'&&notificationRead){if(!mutationAllowed(req,res,session))return;const updated=await query('UPDATE notifications SET read_at=now() WHERE id=$1 AND recipient_id=$2 RETURNING id,read_at',[notificationRead[1],user.id]);if(!updated.rowCount)return json(res,404,{error:{code:'NOT_FOUND',message:'Notification not found.'}});return json(res,200,{notification:updated.rows[0]})}
  if(req.method==='GET'&&url.pathname==='/api/messages'){const relationship=activeRelationship(user,url.searchParams.get('traineeId'));if(!relationship)return json(res,200,{messages:[],relationship:null});const result=await query('SELECT m.id,m.sender_id,u.name AS sender_name,m.body,m.read_at,m.created_at FROM messages m JOIN users u ON u.id=m.sender_id WHERE m.relationship_trainer_id=$1 AND m.relationship_trainee_id=$2 ORDER BY m.created_at ASC LIMIT 200',[relationship.trainerId,relationship.traineeId]);return json(res,200,{messages:result.rows,relationship})}
  if(req.method==='POST'&&url.pathname==='/api/messages'){if(!mutationAllowed(req,res,session))return;const body=await readJson(req,res);if(!body)return;const relationship=activeRelationship(user,body.traineeId);if(!relationship)return json(res,403,{error:{code:'MESSAGE_FORBIDDEN',message:'An active coaching relationship is required.'}});const messageBody=String(body.body||'').trim();if(messageBody.length<1||messageBody.length>2000)return json(res,422,{error:{code:'MESSAGE_INVALID',message:'Message must be 1–2000 characters.'}});if(!rateLimit(`message:${user.id}`,30,60000))return json(res,429,{error:{code:'RATE_LIMITED',message:'Too many messages. Slow down.'}});const message={id:id('message'),sender_id:user.id,sender_name:user.name,body:messageBody,created_at:new Date().toISOString(),read_at:null};await query('INSERT INTO messages(id,relationship_trainer_id,relationship_trainee_id,sender_id,body,created_at) VALUES($1,$2,$3,$4,$5,$6)',[message.id,relationship.trainerId,relationship.traineeId,user.id,message.body,message.created_at]);const recipientId=user.id===relationship.trainerId?relationship.traineeId:relationship.trainerId;await query("INSERT INTO notifications(id,recipient_id,event_type,title,body) VALUES($1,$2,'NEW_MESSAGE',$3,$4)",[id('notification'),recipientId,`New message from ${user.name}`,message.body.slice(0,140)]);return json(res,201,{message})}
  if(req.method==='GET'&&url.pathname==='/api/subscription'){const result=await query('SELECT id,plan_code,status,provider,current_period_end FROM subscriptions WHERE user_id=$1',[user.id]);return json(res,200,{subscription:result.rows[0]||{plan_code:'STARTER',status:'TRIALING',provider:'TEST'}})}
  if(req.method==='POST'&&url.pathname==='/api/billing/test-checkout'){if(!mutationAllowed(req,res,session)||!requireRole(res,user,'TRAINER'))return;const body=await readJson(req,res);if(!body)return;const plan=String(body.planCode||'');if(!['PRO','TEAM'].includes(plan))return json(res,422,{error:{code:'PLAN_INVALID',message:'Choose a valid paid plan.'}});const subscription={id:id('subscription'),plan_code:plan,status:'ACTIVE',provider:'TEST',current_period_end:new Date(Date.now()+30*86400000).toISOString()};await query("INSERT INTO subscriptions(id,user_id,plan_code,status,provider,current_period_end) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(user_id) DO UPDATE SET plan_code=$3,status=$4,provider=$5,current_period_end=$6,updated_at=now()",[subscription.id,user.id,subscription.plan_code,subscription.status,subscription.provider,subscription.current_period_end]);return json(res,201,{subscription,mode:'TEST',message:'No payment was charged.'})}
  return json(res,404,{error:{code:'NOT_FOUND',message:'Resource not found.'}});
}

async function serveStatic(req,res,url){const requested=url.pathname==='/'?'index.html':decodeURIComponent(url.pathname.slice(1));const safe=normalize(requested).replace(/^(\.\.(\/|\\|$))+/,'');const path=join(ROOT,safe);if(!path.startsWith(ROOT))return json(res,403,{error:{code:'FORBIDDEN',message:'Invalid path.'}});try{const info=await stat(path);if(!info.isFile())throw new Error('not file');const body=await readFile(path),etag=`"${createHash('sha256').update(body).digest('base64url').slice(0,20)}"`,cacheControl=extname(path)==='.html'?'no-store':'public, max-age=300, must-revalidate';securityHeaders(res,{cacheControl});res.setHeader('ETag',etag);res.setHeader('Content-Type',types[extname(path)]||'application/octet-stream');if(req.headers['if-none-match']===etag){res.statusCode=304;return res.end()}res.statusCode=200;res.setHeader('Content-Length',body.length);if(req.method==='HEAD')return res.end();res.end(body)}catch{return json(res,404,{error:{code:'NOT_FOUND',message:'Page not found.'}})}}
const server=http.createServer(async(req,res)=>{const started=performance.now(),requestId=typeof req.headers['x-request-id']==='string'&&/^[A-Za-z0-9_-]{1,64}$/.test(req.headers['x-request-id'])?req.headers['x-request-id']:id('req');res.setHeader('X-Request-ID',requestId);res.once('finish',()=>{const durationMs=performance.now()-started;telemetry.requests+=1;telemetry.totalDurationMs+=durationMs;telemetry.byStatus.set(res.statusCode,(telemetry.byStatus.get(res.statusCode)||0)+1);if(res.statusCode>=500)telemetry.errors+=1;if(!['/healthz','/readyz','/metrics'].includes(req.url?.split('?')[0]))log(res.statusCode>=500?'error':'info','http_request',{requestId,method:req.method,route:routeLabel(req.url?.split('?')[0]),status:res.statusCode,durationMs:Number(durationMs.toFixed(2))})});try{if(!['GET','HEAD','POST','PATCH','DELETE'].includes(req.method)){res.setHeader('Allow','GET, HEAD, POST, PATCH, DELETE');return json(res,405,{error:{code:'METHOD_NOT_ALLOWED',message:'Method not allowed.'}})}const url=new URL(req.url,APP_ORIGIN);if(req.method==='GET'&&url.pathname==='/healthz')return json(res,200,{status:'ok',uptimeSeconds:Math.round((Date.now()-telemetry.startedAt)/1000)});if(req.method==='GET'&&url.pathname==='/readyz'){const result=await query('SELECT 1 AS healthy');return json(res,200,{status:'ready',database:databaseMode(),healthy:result.rows[0]?.healthy===1})}if(req.method==='GET'&&url.pathname==='/metrics'){if(IS_PRODUCTION&&req.headers.authorization!==`Bearer ${process.env.METRICS_TOKEN}`)return json(res,404,{error:{code:'NOT_FOUND',message:'Resource not found.'}});return textResponse(res,200,metricsPayload(),'text/plain; version=0.0.4; charset=utf-8')}if(url.pathname.startsWith('/api/'))return await api(req,res,url);if(!['GET','HEAD'].includes(req.method))return json(res,405,{error:{code:'METHOD_NOT_ALLOWED',message:'Method not allowed.'}});return await serveStatic(req,res,url)}catch(error){log('error','request_error',{requestId,message:error.message,method:req.method,route:routeLabel(req.url?.split('?')[0])});if(!res.headersSent)json(res,500,{error:{code:'INTERNAL_ERROR',message:'Something went wrong.',requestId}});else res.end()}});
server.listen(PORT,HOST,()=>log('info','server_started',{url:`http://${HOST}:${PORT}`,database:databaseMode()}));
let shuttingDown=false;async function shutdown(signal){if(shuttingDown)return;shuttingDown=true;log('info','server_shutdown_started',{signal});server.close(async()=>{await closeDatabase();log('info','server_shutdown_complete');process.exit(0)});setTimeout(()=>process.exit(1),10000).unref()}
process.on('SIGINT',()=>shutdown('SIGINT'));process.on('SIGTERM',()=>shutdown('SIGTERM'));
