import assert from 'node:assert/strict';
const base='http://127.0.0.1:4173';

class Actor {
  cookie=''; csrf='';
  async request(path,options={}){
    const response=await fetch(base+path,{...options,headers:{...(this.cookie?{Cookie:this.cookie}:{}),...(options.body?{'Content-Type':'application/json'}:{}),...(options.method&&options.method!=='GET'?{'X-CSRF-Token':this.csrf}:{}),...options.headers}});
    const setCookie=response.headers.get('set-cookie');if(setCookie)this.cookie=setCookie.split(';')[0];
    const data=await response.json();if(data.csrfToken)this.csrf=data.csrfToken;return{response,data};
  }
  async session(){return this.request('/api/session')}
  async login(email,password){return this.request('/api/auth/login',{method:'POST',body:JSON.stringify({email,password})})}
}

const anonymous=new Actor();const anonSession=await anonymous.session();assert.equal(anonSession.response.status,200);assert.equal(anonSession.data.authenticated,false);assert.match(anonSession.response.headers.get('content-security-policy'),/frame-ancestors 'none'/);
const health=await anonymous.request('/healthz');assert.equal(health.response.status,200);assert.equal(health.data.status,'ok');const readiness=await anonymous.request('/readyz');assert.equal(readiness.response.status,200);assert.equal(readiness.data.status,'ready');assert.equal(readiness.data.healthy,true);
const tracedHealth=await fetch(base+'/healthz',{headers:{'X-Request-ID':'smoke_request_123'}});assert.equal(tracedHealth.headers.get('x-request-id'),'smoke_request_123');const metricsResponse=await fetch(base+'/metrics');assert.equal(metricsResponse.status,200);assert.match(await metricsResponse.text(),/ptrainer_http_requests_total/);const staticAsset=await fetch(base+'/app.js');assert.match(staticAsset.headers.get('cache-control'),/max-age=300/);const etag=staticAsset.headers.get('etag');assert.ok(etag);const cachedAsset=await fetch(base+'/app.js',{headers:{'If-None-Match':etag}});assert.equal(cachedAsset.status,304);
const deniedDashboard=await anonymous.request('/api/dashboard');assert.equal(deniedDashboard.response.status,401);
const csrfRejected=await fetch(base+'/api/auth/login',{method:'POST',headers:{Cookie:anonymous.cookie,'Content-Type':'application/json'},body:'{}'});assert.equal(csrfRejected.status,403);

const recoveryUser=new Actor();await recoveryUser.session();const recoveryEmail=`recovery-${Date.now()}@example.com`;const recoveryRegister=await recoveryUser.request('/api/auth/register',{method:'POST',body:JSON.stringify({name:'Recovery Test',email:recoveryEmail,password:'OriginalPass1!',role:'TRAINEE'})});assert.equal(recoveryRegister.response.status,201);await recoveryUser.request('/api/auth/logout',{method:'POST',body:'{}'});await recoveryUser.session();
const forgot=await recoveryUser.request('/api/auth/forgot-password',{method:'POST',body:JSON.stringify({email:recoveryEmail})});assert.equal(forgot.response.status,202);assert.ok(forgot.data.demoResetToken);const reset=await recoveryUser.request('/api/auth/reset-password',{method:'POST',body:JSON.stringify({token:forgot.data.demoResetToken,password:'ChangedPass2!'})});assert.equal(reset.response.status,200);const oldPassword=await recoveryUser.login(recoveryEmail,'OriginalPass1!');assert.equal(oldPassword.response.status,401);const newPassword=await recoveryUser.login(recoveryEmail,'ChangedPass2!');assert.equal(newPassword.response.status,200);

const trainer=new Actor();await trainer.session();const trainerLogin=await trainer.login('trainer@ptrainer.local','DemoTrainer1!');assert.equal(trainerLogin.response.status,200);assert.equal(trainerLogin.data.user.role,'TRAINER');
const exerciseCatalog=await trainer.request('/api/exercises?q=kettlebell&limit=20');assert.equal(exerciseCatalog.response.status,200);assert.ok(exerciseCatalog.data.catalogTotal>=180);assert.ok(exerciseCatalog.data.exercises.some(item=>item.name==='Kettlebell swing'&&item.equipment==='Kettlebell'));
const trainerDashboard=await trainer.request('/api/dashboard');assert.equal(trainerDashboard.response.status,200);const traineeId=trainerDashboard.data.clients[0].id;
assert.equal(typeof trainerDashboard.data.assignedCount,'number');assert.ok(Array.isArray(trainerDashboard.data.upcoming));
const template=await trainer.request('/api/workout-templates',{method:'POST',body:JSON.stringify({name:'Smoke Test Strength',description:'Secure test',exercises:[{name:'Goblet squat',sets:3,reps:10,restSeconds:60}]})});assert.equal(template.response.status,201);const searchableTemplates=await trainer.request('/api/workout-templates');assert.equal(searchableTemplates.response.status,200);assert.ok(searchableTemplates.data.templates.some(item=>item.id===template.data.template.id&&item.exercises.some(exercise=>exercise.name==='Goblet squat')));
const assignment=await trainer.request('/api/assigned-workouts',{method:'POST',body:JSON.stringify({templateId:template.data.template.id,traineeId,dueDate:'2026-08-20'})});assert.equal(assignment.response.status,201);
const editedAssignment=await trainer.request(`/api/assigned-workouts/${assignment.data.assignment.id}`,{method:'PATCH',body:JSON.stringify({name:'Edited Smoke Strength',description:'Trainer updated before logging',dueDate:'2026-08-21',exercises:[{name:'Goblet squat updated',sets:4,reps:8,restSeconds:75}]})});assert.equal(editedAssignment.response.status,200);assert.equal(editedAssignment.data.assignment.templateSnapshot.name,'Edited Smoke Strength');const customAssignment=await trainer.request('/api/assigned-workouts/custom',{method:'POST',body:JSON.stringify({traineeId,name:'Direct Daily Workout',description:'Created from Today workout',dueDate:'2026-08-20',exercises:[{name:'Walking lunge',sets:3,reps:12,restSeconds:60}]})});assert.equal(customAssignment.response.status,201);
const invitation=await trainer.request('/api/invitations',{method:'POST',body:JSON.stringify({email:'trainee@ptrainer.local',note:'Join the program.'})});assert.equal(invitation.response.status,201);

const trainee=new Actor();await trainee.session();const traineeLogin=await trainee.login('trainee@ptrainer.local','DemoTrainee1!');assert.equal(traineeLogin.response.status,200);assert.equal(traineeLogin.data.user.role,'TRAINEE');
const forbiddenExerciseCatalog=await trainee.request('/api/exercises');assert.equal(forbiddenExerciseCatalog.response.status,403);const forbiddenTemplateList=await trainee.request('/api/workout-templates');assert.equal(forbiddenTemplateList.response.status,403);const forbiddenTemplate=await trainee.request('/api/workout-templates',{method:'POST',body:JSON.stringify({name:'No access',exercises:[{name:'Test',sets:1,reps:1}]})});assert.equal(forbiddenTemplate.response.status,403);
const forbiddenWorkoutEdit=await trainee.request(`/api/assigned-workouts/${assignment.data.assignment.id}`,{method:'PATCH',body:JSON.stringify({name:'Unauthorized edit',dueDate:'2026-08-22',exercises:[{name:'Tamper',sets:1,reps:1,restSeconds:0}]})});assert.equal(forbiddenWorkoutEdit.response.status,403);
const accepted=await trainee.request(`/api/invitations/${invitation.data.invitation.inviteCode}/accept`,{method:'POST',body:'{}'});assert.equal(accepted.response.status,200);
const assigned=await trainee.request('/api/assigned-workouts');assert.equal(assigned.response.status,200);assert.ok(assigned.data.assignments.some(item=>item.id===assignment.data.assignment.id));
const key=`smoke_workout_${Date.now()}`;const logBody=JSON.stringify({exercises:[{completed:true}]});const firstLog=await trainee.request(`/api/assigned-workouts/${assignment.data.assignment.id}/logs`,{method:'POST',headers:{'Idempotency-Key':key},body:logBody});assert.equal(firstLog.response.status,201);const repeatedLog=await trainee.request(`/api/assigned-workouts/${assignment.data.assignment.id}/logs`,{method:'POST',headers:{'Idempotency-Key':key},body:logBody});assert.equal(repeatedLog.response.status,200);assert.equal(firstLog.data.log.id,repeatedLog.data.log.id);
const lockedWorkoutEdit=await trainer.request(`/api/assigned-workouts/${assignment.data.assignment.id}`,{method:'PATCH',body:JSON.stringify({name:'Must stay locked',dueDate:'2026-08-23',exercises:[{name:'Locked',sets:1,reps:1,restSeconds:0}]})});assert.equal(lockedWorkoutEdit.response.status,409);

const progress=await trainee.request('/api/progress-entries',{method:'POST',body:JSON.stringify({metricType:'weight',value:74.6,unit:'kg',measuredAt:new Date().toISOString(),note:'Smoke test'})});assert.equal(progress.response.status,201);const progressHistory=await trainer.request(`/api/progress-entries?traineeId=${traineeId}`);assert.equal(progressHistory.response.status,200);assert.ok(progressHistory.data.entries.some(item=>item.id===progress.data.entry.id));
const nutrition=await trainee.request('/api/nutrition-entries',{method:'POST',body:JSON.stringify({entryType:'DAILY',description:'Balanced smoke-test day',calories:2150,proteinG:145,carbsG:225,fatG:70,waterMl:2400})});assert.equal(nutrition.response.status,201);const nutritionHistory=await trainer.request(`/api/nutrition-entries?traineeId=${traineeId}`);assert.equal(nutritionHistory.response.status,200);assert.ok(nutritionHistory.data.entries.some(item=>item.id===nutrition.data.entry.id));
const message=await trainee.request('/api/messages',{method:'POST',body:JSON.stringify({body:`Smoke test message ${Date.now()}`})});assert.equal(message.response.status,201);const trainerMessages=await trainer.request('/api/messages');assert.equal(trainerMessages.response.status,200);assert.ok(trainerMessages.data.messages.some(item=>item.id===message.data.message.id));
const notifications=await trainer.request('/api/notifications');assert.equal(notifications.response.status,200);assert.ok(notifications.data.notifications.length>0);const markedRead=await trainer.request(`/api/notifications/${notifications.data.notifications[0].id}/read`,{method:'POST',body:'{}'});assert.equal(markedRead.response.status,200);
const traineeCheckout=await trainee.request('/api/billing/test-checkout',{method:'POST',body:JSON.stringify({planCode:'PRO'})});assert.equal(traineeCheckout.response.status,403);const checkout=await trainer.request('/api/billing/test-checkout',{method:'POST',body:JSON.stringify({planCode:'PRO'})});assert.equal(checkout.response.status,201);assert.equal(checkout.data.mode,'TEST');const subscription=await trainer.request('/api/subscription');assert.equal(subscription.data.subscription.plan_code,'PRO');
const relationshipList=await trainee.request('/api/relationships');assert.equal(relationshipList.response.status,200);const coachingRelationship=relationshipList.data.relationships.find(item=>item.trainerId===trainerLogin.data.user.id);assert.ok(coachingRelationship);const paused=await trainee.request(`/api/relationships/${coachingRelationship.trainerId}/${coachingRelationship.traineeId}`,{method:'PATCH',body:JSON.stringify({status:'PAUSED'})});assert.equal(paused.response.status,200);const blockedMessage=await trainee.request('/api/messages',{method:'POST',body:JSON.stringify({body:'This must be blocked while paused.'})});assert.equal(blockedMessage.response.status,403);const reactivated=await trainee.request(`/api/relationships/${coachingRelationship.trainerId}/${coachingRelationship.traineeId}`,{method:'PATCH',body:JSON.stringify({status:'ACTIVE'})});assert.equal(reactivated.response.status,200);

const logout=await trainee.request('/api/auth/logout',{method:'POST',body:'{}'});assert.equal(logout.response.status,200);const afterLogout=await trainee.request('/api/dashboard');assert.equal(afterLogout.response.status,401);
const ownProfile=await recoveryUser.request('/api/me');assert.equal(ownProfile.response.status,200);const profileUpdate=await recoveryUser.request('/api/me/profile',{method:'PATCH',body:JSON.stringify({name:'Recovery Test Updated',bio:'Pilot profile',goals:'Consistency',specialties:'',preferredUnits:'METRIC',timezone:'America/Toronto'})});assert.equal(profileUpdate.response.status,200);const dataExport=await recoveryUser.request('/api/me/export');assert.equal(dataExport.response.status,200);assert.equal(dataExport.data.user.email,recoveryEmail);assert.equal('passwordHash' in dataExport.data.user,false);const auditEvents=await recoveryUser.request('/api/me/audit-events');assert.equal(auditEvents.response.status,200);assert.ok(auditEvents.data.events.some(item=>item.action==='PERSONAL_DATA_EXPORTED'));const deletion=await recoveryUser.request('/api/me/account',{method:'DELETE',body:JSON.stringify({password:'ChangedPass2!',confirmation:'DELETE PTRAINER ACCOUNT'})});assert.equal(deletion.response.status,200);await recoveryUser.session();const deletedLogin=await recoveryUser.login(recoveryEmail,'ChangedPass2!');assert.equal(deletedLogin.response.status,401);
console.log(JSON.stringify({healthAndReadiness:'pass',requestTracing:'pass',prometheusMetrics:'pass',httpCaching:'pass',securityHeaders:'pass',csrf:'pass',authentication:'pass',passwordReset:'pass',roleAuthorization:'pass',exerciseCatalog:'pass',invitationAcceptance:'pass',relationshipLifecycle:'pass',templateAssignment:'pass',directWorkoutCreation:'pass',trainerWorkoutEditing:'pass',completedWorkoutLock:'pass',acidWorkoutLogging:'pass',idempotentLogging:'pass',progressTracking:'pass',nutritionJournal:'pass',notifications:'pass',messaging:'pass',testBilling:'pass',profileManagement:'pass',personalDataExport:'pass',auditTrail:'pass',acidAccountAnonymization:'pass',logout:'pass'},null,2));
